openapi: 3.0.0
info:
  version: '1.0'
  title: "Project_30"
  description: API per eseguire il login.
  license:
    name: G30
servers:
  - url: http://localhost:8888/
    description: Localhost
paths:
  /autentication:
    post:
      description: >-
        Autenticazione delle credenziali. Necessarie la email e una password.
      summary: Login utente
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: 'Username dell utente'
                password:
                  type: string
                  description: 'Password dell utente'
      responses:
        '201':
          description: 'Utente autenticato. Link alla home della pagina'
          headers:
            'Location':
              schema:
                type: string
        '500':
          description: 'Errore nel server'
        '401':
          description: 'Autenticazione fallita'
        
  /signup:
    post:
      description: >-
        Iscrizione nuovo utente. Necessaria email non ancora registrata e una password.
      summary: Iscrizione utente
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  description: 'Username dell utente'
                email:
                  type: string
                  description: 'Email dell utente'
                password:
                  type: string
                  description: 'Password dell utente'
                
      responses:
        '201':
          description: 'Utente registrato con successo'
        '500':
          description: 'Errore registrazione'
        '409':
          description: 'Email già registrata'
        
        

components:
  schemas:
    Utente:
      type: object
        - username
        - email
        - password
      properties:
        username:
          type: string
          description: 'Username dell utente'
        email:
          type: string
          description: 'Email dell utente'
        password:
          type: string
          description: 'Password dell utente'
